### ISSUE TITLE
Contenido página "Metodología"

### ISSUE THREAD

**Issue by daquiroz** [ciudadanointeligente/vigilantes#2]

**Comment by octagrammer** [comment]
La metodología de seguimiento del Acuerdo Nacional de Infancia contempla el monitoreo del total de las 94 medidas comprometidas. Las medidas comprometidas pueden ser de carácter legislativo o administrativo dependiendo de si requieren de la aprobación o no de un proyecto de ley por parte del Congreso para ser cumplidas. Las medidas administrativas pueden ser cumplidas mediante actos que son ejecutados por el Gobierno y sus ministerios.

Las medidas serán monitoreadas en base a tres aspectos:

1. Porcentaje de Cumplimiento: se asigna a cada medida un porcentaje de avance en virtud de la etapa en que se encuentran dentro de los procedimientos legislativos o administrativo que requieren superar para transformarse en decisiones formales, es decir, para convertirse en ley o en el acto administrativo que corresponda. El estado de avance se comprueba a través de medios de verificación acordes a la naturaleza de cada medida disponibles en fuentes oficiales del Gobierno o Congreso.

2. Nota de Calidad: se evaluará la aptitud de los actos efectivos de implementación de las medidas del Acuerdo Nacional para satisfacer los objetivos originalmente expuesto en el documento. Los criterios de calidad de cada medida fueron definidos en un proceso de consulta con más de XX expertos y organizaciones especialistas en las distintas áreas del Acuerdo.

3. Ponderación Total: el peso relativo de cada medida en el porcentaje y nota total de la medición, dependen de la ponderación asignada a cada una en razón de su urgencia e importancia. Esta ponderación se definió en un proceso de consulta con más de XX expertos y organizaciones especialistas en las distintas áreas del Acuerdo.

Ingresa aquí (https://docs.google.com/document/d/1L3sLi7jCwqQ_A4W5qqHnZfE6o8-m1DyYsTqskx5RCQg/edit) para conocer en detalle la metodología de seguimiento del proyecto.
