### ISSUE TITLE
Contenido página "Nosotros"

### ISSUE THREAD

**Issue by daquiroz** [ciudadanointeligente/vigilantes#3]

**Comment by octagrammer** [comment]
Vigilantes por la Infancia está compuesto por cuatro organizaciones de la sociedad civil independientes y comprometidas con el desarrollo integral de los niños y niñas del país. 

La Comunidad de Organizaciones Solidarias, Fundación Ciudadanía Inteligente y el Observatorio para la Confianza nos hemos unido con el apoyo de Fundación Colunga en el esfuerzo de monitorear el cumplimiento de los compromisos asumidos por el Presidente Piñera en el marco del Acuerdo Nacional por la Infancia.

Entendemos que los cambios urgentes en nuestra legislación y sistema de protección de la infancia requieren de la participación activa de la sociedad civil y grupos amplios de la ciudadanía para llegar a puerto de la mejor manera posible. Con este proyecto buscamos entregar información relevante y objetiva para facilitar el involucramiento de más actores al debate sobre las políticas de infancia en el país.

Conoce a las organizaciones participantes del proyecto:
LOGOS ORGANIZACIONES

**Comment by octagrammer** [comment]
Creemos que estamos frente a un momento histórico único donde es posible un país más transparente y con una mejor democracia.
